### ISSUE TITLE
Error in data.table::fread(ld_command)

### ISSUE THREAD

**Issue by lin-penglin** [oliviasabik/RACER#1]
When I use the following command to include the LD information, 

head(RACER::ldRACER(assoc_data = ctla4_gwas_f, rs_col = 2, pops = "EUR", lead_snp = "rs231723"))

It shows the error message:

Error in data.table::fread(ld_command) : 
  Single column input contains invalid quotes. Self healing only effective when ncol>1

I checked my data many times but still have no clue, is there any way to solve it?

Thanks!

**Comment by oliviasabik** [comment]
Thanks for reporting this issue. The programmatic access from LDLink, which RACER uses to get access to the 1000 Genomes Data, changed format, so the issue was not with your data. I've updated the ldRACER function accordingly. 

Happy New Year!

**Comment by testlum** [comment]
Hi there, it seems like I've encountered the same issue as lin-penglin when running the script to determine LD. Oddly enough, it only occurs for a specific gene (ATG4C) while running the script for other eqtls didn't bring up any such issue. Is the error coming from the side of 1000 Genomes format this time as well?

Error in data.table::fread(ld_command) : 
Single column input contains invalid quotes. Self healing only effective when ncol>1
