### ISSUE TITLE
HTTP error 403

### ISSUE THREAD

**Issue by swvanderlaan** [oliviasabik/RACER#5]
Hi,

I am trying to run the following command, but it throws an error.

Command: 

`mark3_bmd_gwas_f_ld = RACER::ldRACER(assoc_data = mark3_bmd_gwas_f, rs_col = 2, pops = "EUR", lead_snp = "rs11623869")`

Error:

`Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) : HTTP error 403.`

How can I fix this?

Thanks!

Sander

**Comment by swvanderlaan** [comment]
Could it be related to the link to the API https://analysistools.nci.nih.gov/LDlink/LDlinkRest/ldproxy?var=rs11623869&pop=EUR&r2_d=r2&token=c0f613f149ab? Has this changed? (Given the website link: https://ldlink.nci.nih.gov/?tab=home).

**Comment by mmkim1210** [comment]
I am also experiencing the same error message

**Comment by ruthtopless** [comment]
if you get the ldRACER code off github and replace this :

``` ld_command = paste0("https://analysistools.nci.nih.gov/LDlink/LDlinkRest/ldproxy?var=", lead_snp,"&pop=",pops,"&r2_d=r2&token=c0f613f149ab")```

with this:
```ld_command = paste0("https://ldlink.nci.nih.gov/LDlinkRest/ldproxy?var=", lead_snp,"&pop=",pops,"&r2_d=r2&token=c0f613f149ab")```

 and the same in a second spot further down. it should work.

**Comment by oliviasabik** [comment]
updated the ldlink api url in the package. thanks for bringing this to my attention and solving it for me.
